export const data = [
  {
    name: "Men",
    location: "men",
    links: [
      "New Arrivals",
      "Featured",
      "Jackets & Coats",
      "Knits",
      "Sweats",
      "Shirts",
      "T-Shirts & Polos",
    ],
    secondary: [
      "Denim",
      "Pants",
      "Overalls",
      "Shorts",
      "Underwear",
      "Accessories",
      "Gadgets",
      "Shoes",
      "Collaborations",
      "Sale",
    ],
  },
  {
    name: "Women",
    location: "women",
    links: [
      "New Arrivals",
      "Featured",
      "Jackets",
      "Knits",
      "Sweats",
      "Shirts",
      "T-Shirts",
    ],
    secondary: [
      "Dresses & Skirts",
      "Denim",
      "Pants",
      "Overalls",
      "Shorts",
      "Underwear",
      "Accessories",
      "Gadgets",
      "Shoes",
      "Collaborations",
      "Sale",
    ],
  },
  {
    name: "Lookbook",
    location: "lookbook",
    links: [],
    secondary: [],
  },
  {
    name: "Journal",
    location: "journal",
    links: ["News", "Collaboration", "Skateboarding", "Music", "radio"],
    secondary: [],
  },
  {
    name: "Stores",
    location: "stores",
    links: ["Carhartt WIP Stores", "Stockists", "Online Stockists"],
    secondary: [],
  },
  {
    name: "Brands",
    location: "brands",
    links: [],
    secondary: [],
  },
];
