export const data = [
  {
    name: "Men",
    location: "men",
    links: [
      "New Arrivals",
      "Featured",
      "Jackets & Coats",
      "Knits",
      "Sweats",
      "Shirts",
      "T-Shirts & Polos",
    ],
    secondary: [
      "Denim",
      "Pants",
      "Overalls",
      "Shorts",
      "Underwear",
      "Accessories",
      "Gadgets",
      "Shoes",
      "Collaborations",
      "Sale",
    ],
    linkLocation: ["women-new", "featured"],
  },
  {
    name: "Women",
    location: "women",
    links: [
      "New Arrivals",
      "Featured",
      "Jackets",
      "Knits",
      "Sweats",
      "Shirts",
      "T-Shirts",
    ],
    secondary: [
      "Dresses & Skirts",
      "Denim",
      "Pants",
      "Overalls",
      "Shorts",
      "Underwear",
      "Accessories",
      "Gadgets",
      "Shoes",
      "Collaborations",
      "Sale",
    ],
    linkLocation: ["men-new", "featured"],
  },
];
